export const FETCH_TASK = "FETCH_TASK";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAILED = "FETCH_TASK_FAILED";

export const ON_LOADING = "ON_LOADING";
export const OFF_LOADING = "OFF_LOADING";

export const STATUS_CODE = {
  SUCCESS: 200,
  CREATED: 201,
  UPDATE: 202,
};
